"""test

Revision ID: 7f1914f81f1c
Revises: d9ec325a64ee
Create Date: 2023-09-28 23:58:24.896258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1914f81f1c'
down_revision = 'd9ec325a64ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.CHAR(length=8),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
